version: '3'

services:

  hewwod-nginx:
    container_name: hewwod-nginx
    build:
      context: ./dockerfiles
      dockerfile: Dockerfile-nginx
    volumes:
      - ./etc/nginx/sites/local.conf:/etc/nginx/conf.d/default.conf
      - ./etc/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./static:/usr/share/nginx/html
      - ./keys/dh-param/dhparam-2048.pem:/etc/ssl/certs/dhparam-2048.pem
      - ./keys/letsencrypt/hewwod.com/fullchain.pem:/etc/letsencrypt/live/hewwod.com/fullchain.pem
      - ./keys/letsencrypt/hewwod.com/privkey.pem:/etc/letsencrypt/live/hewwod.com/privkey.pem
      - ./static/letsencrypt:/data/letsencrypt
      - ./var/log/nginx:/var/log/nginx
    depends_on:
      - "hewwod-api"
    ports:
      - "80:80"
      - "443:443"
    networks:
      - app-network
    restart: always

  hewwod-mongo:
    container_name: hewwod-mongo
    build:
      context: ./dockerfiles
      dockerfile: Dockerfile-mongo
    ports:
      - "27017:27017"
    expose:
      - "27017"
    networks:
      - app-network
    restart: always

  hewwod-api:
    container_name: hewwod-api
    build:
      context: ./dockerfiles
      dockerfile: Dockerfile-api
    volumes:
      - ./app:/home/node/app
      - ./config:/home/node/app/config
      - ./node_modules:/home/node/app/node_modules
    environment:
      - NODE_ENV=production
    command: "node api.js"
    depends_on:
      - "hewwod-mongo"
    ports:
      - "3001:3001"
    networks:
      - app-network
    restart: always

  hewwod-rss:
    container_name: hewwod-rss
    build:
      context: ./dockerfiles
      dockerfile: Dockerfile-rss
    volumes:
      - ./services:/home/node/app
      - ./config:/home/node/app/config
      - ./node_modules:/home/node/app/node_modules
    environment:
      - NODE_ENV=production
    command: "node rss-wod-parser.js"
    depends_on:
      - "hewwod-mongo"
    networks:
      - app-network
    restart: always

  hewwod-notifications:
    container_name: hewwod-notifications
    build:
      context: ./dockerfiles
      dockerfile: Dockerfile-notifications
    volumes:
      - ./services:/home/node/app
      - ./config:/home/node/app/config
      - ./node_modules:/home/node/app/node_modules
    environment:
      - NODE_ENV=production
    command: "node notifications.js"
    depends_on:
      - "hewwod-mongo"
    networks:
      - app-network
    restart: always

  letsencrypt-nginx-container:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./etc/nginx/sites/letsencrypt.conf:/etc/nginx/conf.d/default.conf
      - ./static/letsencrypt:/usr/share/nginx/html
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
